# Generated by Django 3.0.6 on 2020-06-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='User',
            new_name='user',
        ),
    ]
